//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Customer_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    public partial class CustomerInfo
    {
        [Key]
        [DisplayName("Customer ID")]
        public int Cust_Id { get; set; }

        [DisplayName("Customer Name")]
        [Required(ErrorMessage = "Name is required")]
        public string CustName { get; set; }

        [DisplayName("Password")]
        [Required(ErrorMessage = "Password is required")]
        //[DataType(DataType.Password)]
        public string Password { get; set; }

        [DisplayName("Mobile Number")]
        [Required(ErrorMessage = "Mobile Number is required")]
        [RegularExpression(@"^([0-9]{10})$", ErrorMessage = "Invalid Mobile Number.")]
        public long Mobile_No { get; set; }

        [DisplayName("Gender")]
        [Required(ErrorMessage = "Gender is required")]
        public string Gender { get; set; }

        [DisplayName("Age")]
        [Required(ErrorMessage = "Age is required")]
        [Range(0,110)]
        public int Age { get; set; }

        [DisplayName("Email Id")]
        [Required(ErrorMessage = "Email ID is required")]
        [EmailAddress(ErrorMessage = "Invalid Email Address.")]
        public string Email_Id { get; set; }
    }
}
